table! {
    use crate::diesel::sql_types::*;
    use crate::exports::Article_status;

    /// Representation of the `articles` table.
    ///
    /// (Automatically generated by Diesel.)
    articles (id) {
        /// The `id` column of the `articles` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `user_id` column of the `articles` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Int4,
        /// The `title` column of the `articles` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Varchar,
        /// The `body` column of the `articles` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        body -> Varchar,
        /// The `publication_time` column of the `articles` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        publication_time -> Timestamptz,
        /// The `modification_time` column of the `articles` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        modification_time -> Timestamptz,
        /// The `status` column of the `articles` table.
        ///
        /// Its SQL type is `Article_status`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Article_status,
    }
}

table! {
    use crate::diesel::sql_types::*;
    use crate::exports::Article_status;

    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `user_name` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        user_name -> Varchar,
        /// The `user_pic` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        user_pic -> Varchar,
    }
}

joinable!(articles -> users (user_id));

allow_tables_to_appear_in_same_query!(articles, users,);
